Javascript Card Game
Ceegees/training pull request #2
Opened 2017-07-11 09:10 UTC by Puvikaran

Still card values to be sort and sum

2017-07-12 04:58 UTC, giju reviewed
let me know once the changes are made

2017-07-12 04:58 UTC, giju commented on Puvikaran/cardgame.js
> +        function Card(values, suites) {
externalise this class and add associated functions to the class.

2017-07-12 04:58 UTC, giju commented on Puvikaran/cardgame.js
> +        function Shuffle() {
make this a method of the deck class

2017-07-12 04:58 UTC, giju commented on Puvikaran/cardgame.js
> +        function makeDeck() {
make this the constructor of deck

2017-07-12 04:58 UTC, giju commented on Puvikaran/cardgame.js
> +        function removeCard() {
move these functions to deck / player

2017-07-12 05:04 UTC, giju requested changes
move all classes to separate files , Once you have made the changes let me know

2017-07-13 15:59 UTC, Puvikaran commented
Card values calculated and Players sorted based on card values,
Files Separated and the remaining changes mentioned needs to be done 
![cardgame](https://user-images.githubusercontent.com/20906828/28175551-34233b96-6812-11e7-81d6-fd3696d928c5.png)

2017-07-31 13:03 UTC, merged